name = "brilo"
version = "1.0.2"

description = "A collection of various functions missing in gleam_stdlib"
licences = ["GPL-3.0-or-later"]
repository = { type = "github", user = "l-x", repo = "brilo" }

gleam = ">= 1.4.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
